<?php 
	$this->headScript()->appendFile(URL_SCRIPTS . '/ckeditor/ckeditor.js', 'text/javascript');
?>

<!-- BUTTON -->
<?php echo $this->render('area_toolbar.phtml'); ?>

<!-- NOTICE -->
<?php echo $this->flashMessenger()->render();?>
<?php echo $this->myForm->showMessage();?>

<div class="box box-info">
	<div class="box-body">
		<?php
			$myForm				= $this->myForm;
			$myForm->prepare();
			echo $this->form()->openTag($myForm);
				echo $this->partialLoop('form_row.phtml', array(
						array('elm' => $myForm->get('username')),
						array('elm' => $myForm->get('email')),
						array('elm' => $myForm->get('fullname')),
						array('elm' => $myForm->get('password')),
						array('elm' => $myForm->get('group')),
						array('elm' => $myForm->get('file')),
						array('elm' => $myForm->get('avatar'), 'type' => 'avatar'),
						array('elm' => $myForm->get('ordering')),
						array('elm' => $myForm->get('status')),
						array('elm' => $myForm->get('sign')),
						array('elm' => $myForm->get('id'), 'type' => 'hidden'),
						array('elm' => $myForm->get('action'), 'type' => 'hidden'),
						array('elm' => $myForm->get('avatar'), 'type' => 'hidden'),
				));
			echo $this->form()->closeTag();
		?>
	</div>
</div>

<?php echo $this->headScript()->captureStart();?>
	CKEDITOR.replace( 'sign' , {
		customConfig	: '<?php echo URL_SCRIPTS . '/ckeditor'?>' + '/config-user-sign.js'
	});
<?php echo $this->headScript()->captureEnd();?>






