<?php 
	if($this->_data->count() == 0 ) return null;
	
	$xhtml = '';
	$cmsInfoPrice	= $this->getView()->plugin('cmsInfoPrice');
	$linkBook		= $this->getView()->plugin('linkBook');
	$cmsPriceReal	= $this->getView()->plugin('cmsPriceReal');
	$urlHelper		= $this->getView()->plugin('url');
	
	$i = 1;
	foreach ($this->_data as $book){
		$imgUrl			= URL_FILES . '/books/thumb/140x190/' . $book->picture;
		$name			= $book->name;
		$linkInfoBook	= $linkBook($book->id, $book->name, $book->category_name);
		$linkPopup		= $urlHelper('shopRoute/default',array('controller' => 'book', 'action' => 'popup'));
		
		$price			= $cmsInfoPrice($book->price, $book->sale_off, array('task' => 'price-frontend'));
		
		$classLI		= '';
		if($i == 1 || $i == 4) $classLI	= 'first-in-line';
		if($i == 3 || $i == 6) $classLI	= 'last-in-line';
		if($i >= 4) $classLI	.= ' last_line';
		
		$linkAddToCart	= $urlHelper('shopRoute/order',array(
				'id' 		=> $book->id,
				'price' 	=> $cmsPriceReal($book->price, $book->sale_off),
				'quantity'	=> 1,
		));
		
		$xhtml .= '<li class="'.$classLI.' col-sm-4">
						<div class="padding">
							<div class="image2">
								<a href="'.$linkInfoBook.'"><img id="img_32" src="'.$imgUrl.'" alt="'.$name.'"></a>
							</div>
	
							<a href="'.$linkPopup.'" data-id="'.$book->id.'" class="colorbox quick-view-button cboxElement"><i class=" fa fa-search "></i></a>
										
							<div class="inner">
								<div class="f-left">
									<div class="price">'.$price.'</div>
									<div class="name maxheight-feat" style="min-height: 44px;">
										<a href="'.$linkInfoBook.'">'.$name.'</a>
									</div>
								</div>
								<div class="cart-button">
									<div class="cart">
										<a title="Add to cart" href="'.$linkAddToCart.'" class="button addToCart">
											<span>Add to cart</span></a>
									</div>
									<span class="clear"></span>
								</div>
								<div class="clear"></div>
							</div>
							<div class="clear"></div>
						</div>
					</li>';
		$i++;
	}
?>

<div class="box featured">
	<div class="box-heading">New book</div>
	<div class="box-content">
		<div class="box-product">
			<ul class="row">
				<?php echo $xhtml;?>
			</ul>
		</div>
		<div class="clear"></div>
	</div>
</div>