<div class="box info">
	<div class="box-content" style="padding:10px">
		<div id="fb-root"></div>
		<script>(function(d, s, id) {
		  var js, fjs = d.getElementsByTagName(s)[0];
		  if (d.getElementById(id)) return;
		  js = d.createElement(s); js.id = id;
		  js.src = "//connect.facebook.net/vi_VN/sdk.js#xfbml=1&version=v2.0";
		  fjs.parentNode.insertBefore(js, fjs);
		}(document, 'script', 'facebook-jssdk'));</script>
		<div class="fb-like-box"
			data-href="https://www.facebook.com/zendvngroup" data-width="250"
			data-colorscheme="light" data-show-faces="true" data-header="false"
			data-stream="false" data-show-border="false"></div>
	</div>
</div>